# Uncomment the next line to define a global platform for your project
# platform :ios, '14.1'
use_frameworks!

target 'SkillBoxLesson4' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SkillBoxLesson4

pod 'RealmSwift'
pod 'Realm'


  target 'SkillBoxLesson4Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SkillBoxLesson4UITests' do
    # Pods for testing
  end

end
